transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib niosLab2
vmap niosLab2 niosLab2
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/niosLab2.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_pio_2.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_pio_1.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_onchip_memory2_1.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_onchip_memory2_0.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_nios2_gen2_0.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_nios2_gen2_0_cpu_test_bench.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_nios2_gen2_0_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_nios2_gen2_0_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_nios2_gen2_0_cpu.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_nios2_gen2_0_cpu_debug_slave_tck.v}
vlog -vlog01compat -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_jtag_uart_0.v}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_irq_mapper.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_cmd_mux_002.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_router_004.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_router_002.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_router_001.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/niosLab2_mm_interconnect_0_router.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work niosLab2 +incdir+/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/altera_merlin_master_translator.sv}
vcom -93 -work work {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/Lab1_FPGA_RTL.vhd}
vcom -93 -work work {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/LAB2_FPGA_NIOS.vhd}
vcom -93 -work work {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/IP/peripheral_LED.vhd}
vcom -93 -work niosLab2 {/home/labarqcomp/Downloads/github/SoC-e-Linux-Embarcado/Lab3_FPGA_IP/niosLab2/synthesis/submodules/peripheral_LED.vhd}

